project_name: audiobait
dist: dist

release:
  github:
    owner: TheCacophonyProject
    name: audiobait
  name_template: '{{.Tag}}'

builds:
- goos:
  - linux
  goarch:
  - arm
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X main.version={{.Version}}
  binary: audiobait

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

nfpm:
  vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Menno Finlay-Smits <menno@cacophony.org.nz>
  description: Play audio lures
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  dependencies:
    - sox
  bindir: /usr/bin
  files:
    "audiobait.service": "/etc/systemd/system/audiobait.service"
  config_files:
    "audiobait.yaml": "/etc/audiobait.yaml"

archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
  format: tar.gz
  files:
  - audiobait.service
  - audiobait.yaml
